### ISSUE TITLE
청청콘 참가자 사업계획서

### ISSUE THREAD

**Issue by 2-juhyun-2** [wjrmffldrhrl/armagyeddon-frontend#4]
@wjrmffldrhrl @minhyeok3924 @xmxmqq 

오늘까지 보완 수정한 결과

[2. (사업계획서) 청청콘  참가자 사업계획서.zip](https://github.com/wjrmffldrhrl/armagyeddon-frontend/files/5177833/2.zip)

**Comment by xmxmqq** [comment]
## 수정할 부분
> 2.1. 사업화전략 (BM)
- [ ] **핵심파트너** 무선이어폰 '저축계'를 위해 제휴한 @@ 가전업체, 제주도 올레길 투어 패키지 '친목계'를 위해 제휴한 +++ 여행사 등등
- [ ] **핵심활동** 
- [ ] **핵심자원** 블록체인 기술, 웹/앱 프로그래밍 기술 
- [ ] **가치제안** 목표금액, 곗돈수령 순서, 개별맞춤 계방 개설 등 소비자들의 자유로운 금융 생활을 보장하는 플랫폼 서비스 제공
- [ ] **고객관계** 아마곗돈 회원들의 자산증대와 타 제휴업체와의 상생 도모
- [ ] **채널** ① 2030대 층)Youtube, Facebook, Instagram, TicToc, ② 40대~) Blog, Cafe, naver Band
- [ ] **고객구분**  ① 보통 및 당좌 예금 형식의 현금 유동성이 주목적인 회원, ② 제 1금융권에 준하는 이자율을 기대하는 회원, ③ 지인들과 안전한 계모임 문화를 즐기고 싶은 회원, ④ 혁신적인 금융 플랫폼을 통해 저축 동기부여가 필요한 회원
- [ ] **비용** ① 인건비, ② 구현, 배포, 서버관리 비용, ③ 홍보 비용 등
- [ ] **수익** 
> 2.1. 사업추진일정 
- [ ] (공모전 종료 일자인 11월 19일을 데드라인으로 작성해야 할 듯 싶으나 추후 재논의 필요)
> 3.1. 내수시장 확보 방안
* 주 소비층 : 유스층을 적극 활용
- [ ] 전통적인 계 모임을 현대적으로 재해석하여 유스층을 초기 타겟으로 잡고 부모님 세대로 소비자 연령대 폭을 확대 
- [ ] SNS와 비대면에 친숙한 유스층과 현금흐름에 대한 풍부한 지식 및 금융 시스템에 노출이 큰 장년층의 특징이 상호보완되어 온 세대가 공유하는 하나의 문화로 자리잡을 수 있도록 유튜브 채널로 홍보할 계획
* 주 타겟시장 및 진출 시기
- [ ] 국내 p2p 시장: 완전한 웹 시제품이 완료된 2020 11월 중순
- [ ] 국내 금융 시장: 앱 구현이 완료된 2021 하반기
- [ ] 해외 금융 시장: (내수시장 출시와 병렬로 진행) 2021 하반기

**Comment by xmxmqq** [comment]
홍보 방법으로 체험단이나 대학생 대외활동 등과 같은 내용을 첨부하고 싶은데 어느 항목이 적합할 지 혼란스러워 의견공유해 주시면 감사하겠습니다

**Comment by 2-juhyun-2** [comment]
내맘대로 최종
@xmxmqq @wjrmffldrhrl @minhyeok3924 
[Armagyeddon청청콘사업계획서.zip](https://github.com/wjrmffldrhrl/armagyeddon-frontend/files/5216368/Armagyeddon.zip)

**Comment by wjrmffldrhrl** [comment]
Plz move this issue to [backend repository](https://github.com/wjrmffldrhrl/armagyeddon-backend/issues/32)
